development:
  adapter: postgresql
  encoding: unicode
  database: language_penpal_api_dev
  pool: 5


# test:
#   adapter: postgresql
#   encoding: unicode
#   database: language_penpal_api_test
#   pool: 5
